Login and Push

diff --git a/.github/actions/dockerHub/action.yml b/.github/actions/dockerHub/action.yml
--- a/.github/actions/dockerHub/action.yml
+++ b/.github/actions/dockerHub/action.yml
@@ -25,6 +25,18 @@ runs:
         username: ${{ inputs.dockerhub_username }}
         password: ${{ inputs.dockerhub_token }}
 
+    - name: Build Docker image
+      shell: bash
+      run: |
+        IMAGE_NAME="${{ inputs.image_name }}"
+        if [ -z "$IMAGE_NAME" ]; then
+          echo "Error: IMAGE_NAME is not set."
+          exit 1
+        fi
+        # Build the image
+        docker build . --file "${{ inputs.path_dockerfile }}" --tag "$IMAGE_NAME:latest"
+
+
     - name: Re-tag docker image
       shell: bash
       run: |
@@ -34,11 +46,11 @@ runs:
           exit 1
         fi
         SOURCE_IMAGE="${IMAGE_NAME}:latest"  # Ensure the SOURCE_IMAGE is defined correctly
-        TAGGED_IMAGE="${{ inputs.dockerhub_username }}/${IMAGE_NAME}:latest"
+        TAGGED_IMAGE="${{ inputs.dockerhub_username }}/${IMAGE_NAME}"
         docker tag "$SOURCE_IMAGE" "$TAGGED_IMAGE"
 
     - name: Push Docker image
       shell: bash
       run: |
-        TAGGED_IMAGE="${{ inputs.dockerhub_username }}/${{ inputs.image_name }}:latest"
+        TAGGED_IMAGE="${{ inputs.dockerhub_username }}/${{ inputs.image_name }}"
         docker push "$TAGGED_IMAGE"
